CREATE TABLE Project (
    id INTEGER NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE Reference (
    id INTEGER NOT NULL PRIMARY KEY
);

CREATE TABLE Ticket (
    id INTEGER NOT NULL PRIMARY KEY,
    ticket_kkey VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    workspace VARCHAR(100) NOT NULL,
    status_id INTEGER NOT NULL
);

CREATE TABLE Link (
    id INTEGER NOT NULL PRIMARY KEY,
    ticket_id INTEGER NOT NULL,
    link VARCHAR(100) NOT NULL
);

CREATE TABLE Attachment (
    id INTEGER NOT NULL PRIMARY KEY,
    ticket_id INTEGER NOT NULL,
    link VARCHAR(100) NOT NULL
);

CREATE TABLE Progress (
    id INTEGER NOT NULL PRIMARY KEY,
    ticket_id INTEGER NOT NULL,
    progress_date VARCHAR(100) NOT NULL,
    report VARCHAR(100) NOT NULL
);

CREATE TABLE Task (
    id INTEGER NOT NULL PRIMARY KEY,
    ticket_id INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL,
    workspace VARCHAR(100) NOT NULL,
    status_id INTEGER NOT NULL
);

CREATE TABLE Status (
    id INTEGER NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);